"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AbortError = void 0;
exports.createRetryWrapper = createRetryWrapper;
const async_retry_1 = __importDefault(require("async-retry"));
const CustomErrors_1 = require("../errors/CustomErrors");
// Custom error class to signal that retries should be aborted
class AbortError extends Error {
    constructor() {
        super(...arguments);
        this.name = 'AbortError';
        this.aborted = true;
    }
}
exports.AbortError = AbortError;
/**
 * Creates a retry wrapper for API requests
 * @param config SDK configuration containing retry settings
 * @returns Function that wraps API calls with retry logic
 */
function createRetryWrapper(config) {
    return function retryWrapper(fn) {
        return async (url, options) => {
            return (0, async_retry_1.default)(async (bail, attemptNumber) => {
                if (config.logging) {
                    console.log(`Attempt ${attemptNumber} starting...`);
                }
                try {
                    return await fn(url, options);
                }
                catch (error) {
                    const err = error;
                    // Don't retry on validation errors or auth errors
                    if (err instanceof CustomErrors_1.ValidationError || err instanceof CustomErrors_1.AuthError) {
                        bail(new AbortError(err.message));
                        throw new AbortError(err.message); // This will never execute but satisfies TypeScript
                    }
                    // Retry on configured status codes
                    if (err.statusCode && config.retryStatusCodes.includes(err.statusCode)) {
                        if (config.logging) {
                            console.log(`Retrying due to status code ${err.statusCode}`);
                        }
                        throw err;
                    }
                    // Retry on network errors
                    if (err instanceof CustomErrors_1.NetworkError || err instanceof CustomErrors_1.TimeoutError) {
                        if (config.logging) {
                            console.log(`Retrying due to network/timeout error: ${err.message}`);
                        }
                        throw err;
                    }
                    // Don't retry on other errors
                    bail(new AbortError(err.message));
                    throw new AbortError(err.message); // This will never execute but satisfies TypeScript
                }
            }, {
                retries: config.maxRetries,
                factor: config.retryBackoffFactor / 1000, // Convert ms to seconds
                minTimeout: 1000,
                maxTimeout: 60000,
                randomize: true,
                onRetry: (error, attemptNumber) => {
                    if (config.logging) {
                        console.log(`Attempt ${attemptNumber} failed. Retrying...`);
                    }
                },
            });
        };
    };
}
//# sourceMappingURL=retry.js.map